In [95]:
hyper_parameter = {"a":3, "b":"birthday", "c":[1,2,3,4,5]}

def explanin1(a, b, c):
    res1 =a
    res2 =b
    res3 =c
    return res1, res2, res3

explanin1(**hyper_parameter)
def explanin2(param):
    return {**param, "d":30}
explanin2(hyper_parameter)


{'a': 3, 'b': 'birthday', 'c': [1, 2, 3, 4, 5], 'd': 30}

In [96]:
import numpy as np
from transformers.trainer_utils import EvalPrediction

def accuracy_score(predict):
    preds = np.argmax(predict.predictions, axis=1)
   
    acc = (preds == predict.label_ids).mean()
    return {"accuracy": acc}

y_hat = np.array([[0.2, 0.8], [0.4, 0.6], [0.1, 0.9]])
y_true = np.array([1, 0, 1])

pred = EvalPrediction(predictions=y_hat, label_ids=y_true)
print(pred.predictions)
print(pred.label_ids)

print(vars(pred))

print(pred.__dict__)
accuracy_score(pred)

[[0.2 0.8]
 [0.4 0.6]
 [0.1 0.9]]
[1 0 1]
{'predictions': array([[0.2, 0.8],
       [0.4, 0.6],
       [0.1, 0.9]]), 'label_ids': array([1, 0, 1]), 'inputs': None, 'losses': None, 'elements': (array([[0.2, 0.8],
       [0.4, 0.6],
       [0.1, 0.9]]), array([1, 0, 1]))}
{'predictions': array([[0.2, 0.8],
       [0.4, 0.6],
       [0.1, 0.9]]), 'label_ids': array([1, 0, 1]), 'inputs': None, 'losses': None, 'elements': (array([[0.2, 0.8],
       [0.4, 0.6],
       [0.1, 0.9]]), array([1, 0, 1]))}


{'accuracy': np.float64(0.6666666666666666)}

In [106]:
import  torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

#model_name  = "beomi/kcbert-base"
model_name = "monologg/koelectra-base-v3-finetuned-korquad"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

tokenizer_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

c:\Users\User\.conda\envs\GenAI2503\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\User\.cache\huggingface\hub\models--monologg--koelectra-base-v3-finetuned-korquad. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config.json:   0%|          | 0.00/591 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/449M [00:00<?, ?B/s]

Some weights of ElectraForSequenceClassification were not initialized from the model checkpoint at monologg/koelectra-base-v3-finetuned-korquad and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [98]:
text = "이 영화 너무 좋았어! 최고야!"
inputs = tokenizer(text, return_tensors="pt")

In [99]:
inputs

{'input_ids': tensor([[    2,  2451,  9376,  8069, 12307,  4071,     5,  8619,  4144,     5,
             3]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [100]:
inputs.input_ids

tensor([[    2,  2451,  9376,  8069, 12307,  4071,     5,  8619,  4144,     5,
             3]])

In [101]:
inputs.token_type_ids

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [102]:
inputs.attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [103]:
model.eval()
with torch.no_grad():
    outputs = model(**inputs)

In [104]:
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-0.1094, -0.2511]]), hidden_states=None, attentions=None)

In [105]:
outputs.logits

tensor([[-0.1094, -0.2511]])

In [61]:
logits = outputs.logits
sentiment = torch.argmax(logits, dim=1).item()
print("결과:", "긍정" if sentiment == 1 else "부정")

결과: 긍정
